repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: detect-private-key
      - id: check-ast

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [--config-file=mypy.ini]
