[tool.aerich]
tortoise_orm = "database.postgres.core.tortoise_config.TORTOISE_ORM"
location = "./database/postgres/migrations"
src_folder = "./."

[tool.ruff]
select = ["I", "F", "E", "W", "UP", "C4", "B"]
ignore = []
line-length = 120
exclude = ["migrations", "venv"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = "-ra --strict-markers"