name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest ruff mypy

    - name: Run Ruff
      run: ruff .

    - name: Run Mypy
      run: mypy .

    - name: Run Pytest
      run: pytest
