name: Manual Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        run: |
          rsync -a . ${{ secrets.APP_DEPLOY_PATH }}
          cd ${{ secrets.APP_DEPLOY_PATH }}
          source .venv/bin/activate
          pip install -r requirements.txt
          systemctl restart nasa-bot.service
